services:
  - type: worker
    name: invitgene-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        value: sqlite+aiosqlite:///invitgenebot.db
      - key: DEFAULT_CURRENCY
        value: USD
